"""Export the comparison figures as pgfplots source for the manuscript.

The figures are produced twice: as a PNG for reading on screen, and as a
``tikzpicture`` that the paper ``\\input``s. Both are written from the *same*
result objects rather than by converting a rendered Matplotlib figure, so the
two cannot drift and the LaTeX version carries the numbers themselves rather
than a traced approximation of them. The emitted file needs only ``pgfplots``
with the ``groupplots`` library, both already in the manuscript preamble, and no
external data files: the coordinates are inline, so the ``.tex`` is
self-contained and survives being moved.

Colours and markers come from :mod:`dmimo_power.plotting`, so a deployment keeps
one identity across the PNG and the paper, and identity is carried by marker
shape as well as by hue, which is what keeps the panels readable in greyscale
and under colour-vision deficiency. Legend text is plain: a figure that is
``\\input`` into a floating environment should not depend on the expansion state
of an acronym macro.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Sequence

from .plotting import BLOCK_COLOR, DEPLOYMENT_COLOR, DEPLOYMENT_MARKER
from .scenarios import Deployment

#: pgfplots marker names for the Matplotlib codes used in the PNG figures.
_PGF_MARK = {"o": "*", "s": "square*", "D": "diamond*", "^": "triangle*"}

#: Legend text, short enough for four entries on one row.
_PGF_LABEL = {
    Deployment.COLOCATED: "co-located",
    Deployment.CENTRALIZED_S1: "D-MIMO S1",
    Deployment.CENTRALIZED_S2: "D-MIMO S2",
    Deployment.DISTRIBUTED_S3: "D-MIMO S3",
}


def _color_name(deployment: Deployment) -> str:
    return f"clr{deployment.name.replace('_', '')}"


def _color_definitions(deployments: Sequence[Deployment]) -> str:
    """``\\definecolor`` lines for the deployments actually plotted."""
    return "\n".join(
        f"\\definecolor{{{_color_name(d)}}}{{HTML}}"
        f"{{{DEPLOYMENT_COLOR[d].lstrip('#').upper()}}}"
        for d in deployments
    )


def _series(deployment: Deployment, results, x, y) -> str:
    """One ``\\addplot`` with inline coordinates.

    A single-point series is drawn with an open marker and no connecting line,
    so a lone reference point does not read as a truncated curve.
    """
    color = _color_name(deployment)
    mark = _PGF_MARK[DEPLOYMENT_MARKER[deployment]]
    coords = " ".join(f"({x(r):.6g},{y(r):.6g})" for r in results)
    if len(results) == 1:
        style = (f"only marks, mark={mark}, mark size=2.8pt, draw={color}, "
                 f"mark options={{fill=white, draw={color}, line width=1pt}}")
    else:
        style = (f"thick, {color}, mark={mark}, mark size=2.1pt, "
                 f"mark options={{solid, fill={color}, draw=white, line width=0.4pt}}")
    return f"  \\addplot[{style}] coordinates {{{coords}}};"


def rate_vs_power_panels(panels: Dict[str, Dict[Deployment, Sequence]],
                         path, *,
                         xlabel=r"network power $P_{\mathrm{net}}$ [W]",
                         ylabel=r"sum rate $R_{\mathrm{DL}}\!+\!R_{\mathrm{UL}}$ [Gbit/s]",
                         width="0.30\\textwidth", height="4.9cm",
                         xmode="normal") -> Path:
    """Write a one-row ``groupplot`` of delivered rate against power.

    One panel per key, sharing a single legend placed under the middle panel so
    that no panel loses plotting area to it. The y label is drawn once at the
    left edge for the same reason; the y *ticks* stay on every panel, since the
    panels do not share a rate range.

    Args:
        panels: Ordered mapping ``panel title -> {Deployment: [OperatingResult]}``.
            The title should name what distinguishes the panel (the topology)
            and nothing else, since everything else is shared.
        path: Destination ``.tex``.
        xlabel, ylabel: Axis labels, in LaTeX.
        width, height: pgfplots dimensions of one panel.
        xmode: ``"log"`` to put the power axis on a log scale.

    Returns:
        The path written.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    seen = list(dict.fromkeys(d for cols in panels.values() for d in cols))
    n = len(panels)
    middle = (n + 1) // 2   # panel the shared legend hangs under

    out = [
        "% Generated by scripts/eval1_rate_vs_power.py -- do not edit by hand;",
        "% re-run the script so the figure and the numbers stay tied together.",
        "% Requires pgfplots + the groupplots library (already in the preamble).",
        _color_definitions(seen),
        "\\begin{tikzpicture}",
        "\\begin{groupplot}[",
        f"  group style={{group size={n} by 1, horizontal sep=1.1cm,",
        "                ylabels at=edge left},",
        f"  width={width}, height={height},",
        f"  xlabel={{{xlabel}}}, ylabel={{{ylabel}}},",
        f"  xmode={xmode},",
        "  grid=both, grid style={line width=0.2pt, draw=gray!25},",
        "  tick label style={font=\\scriptsize},",
        "  label style={font=\\footnotesize},",
        "  title style={font=\\footnotesize, yshift=-3pt},",
        "  legend style={font=\\footnotesize, draw=none, fill=none, legend columns=4,",
        "                /tikz/every even column/.append style={column sep=8pt}},",
        "]",
    ]

    for i, (title, columns) in enumerate(panels.items()):
        opts = f"title={{{title}}}"
        if i == 0:
            opts += ", legend to name=eval1legend"
        out.append(f"\\nextgroupplot[{opts}]")
        for deployment, results in columns.items():
            if not results:
                continue
            out.append(_series(deployment, list(results),
                               lambda r: r.power, lambda r: r.R_total * 1e-9))
        if i == 0:
            out.append("  \\legend{" + ", ".join(_PGF_LABEL[d] for d in seen) + "}")

    out += [
        "\\end{groupplot}",
        f"\\node[anchor=north, yshift=-1.05cm] at (group c{middle}r1.south)",
        "  {\\pgfplotslegendfromname{eval1legend}};",
        "\\end{tikzpicture}",
        "",
    ]
    path.write_text("\n".join(out), encoding="utf-8")
    return path


def power_vs_aps(results_by_deployment, path, *, colocated_result=None,
                 xlabel=r"number of APs $L$",
                 ylabel=r"network power $P_{\mathrm{net}}$ [W]",
                 width="0.92\\columnwidth", height="5.6cm") -> Path:
    """Write a single axis of network power against the number of APs.

    The x axis is logarithmic in base two, since the sweep doubles ``L`` and the
    interesting comparison is between successive halvings of the array. The
    co-located point is drawn as an open marker at ``L = 1`` rather than as the
    left end of the split curves, because it is a different model: a distributed
    network with one AP would still pay a fronthaul link and a central unit.

    Args:
        results_by_deployment: Mapping ``Deployment -> [OperatingResult]``,
            ordered by AP count.
        path: Destination ``.tex``.
        colocated_result: The single-site reference point, or ``None``.
        xlabel, ylabel: Axis labels, in LaTeX.
        width, height: pgfplots dimensions.

    Returns:
        The path written.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    seen = [d for d, r in results_by_deployment.items() if r]
    legend = list(seen)
    if colocated_result is not None:
        legend = [Deployment.COLOCATED] + legend

    out = [
        "% Generated by scripts/eval23_ap_sweep.py -- do not edit by hand.",
        "% Requires pgfplots (already in the preamble).",
        _color_definitions(legend),
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        f"  width={width}, height={height},",
        f"  xlabel={{{xlabel}}}, ylabel={{{ylabel}}},",
        "  xmode=log, log basis x=2, xtick={1,2,4,8,16,32,64,128},",
        "  xticklabels={1,2,4,8,16,32,64,128},",
        "  grid=both, grid style={line width=0.2pt, draw=gray!25},",
        "  tick label style={font=\\scriptsize},",
        "  label style={font=\\footnotesize},",
        "  legend style={font=\\scriptsize, draw=none, fill=none,",
        "                at={(0.02,0.98)}, anchor=north west, legend columns=1},",
        "]",
    ]
    if colocated_result is not None:
        out.append(_series(Deployment.COLOCATED, [colocated_result],
                           lambda r: 1, lambda r: r.power))
    for deployment in seen:
        out.append(_series(deployment, list(results_by_deployment[deployment]),
                           lambda r: r.L, lambda r: r.power))
    out.append("  \\legend{" + ", ".join(_PGF_LABEL[d] for d in legend) + "}")
    out += ["\\end{axis}", "\\end{tikzpicture}", ""]

    path.write_text("\n".join(out), encoding="utf-8")
    return path


def ee_vs_aps(results_by_deployment, path, *, colocated_result=None, Pi_FH=None,
              xlabel=r"number of APs $L$",
              ylabel=r"$EE_{\mathrm{net}}$ [Mbit/J]",
              width="0.92\\columnwidth", height="5.6cm") -> Path:
    """Write a single axis of energy efficiency against the number of APs.

    Same axis convention as :func:`power_vs_aps`, so the two figures can be laid
    side by side and read together, which is what the manuscript asks of them.
    The y axis is logarithmic: the splits span more than a decade over the
    sweep, and the ceiling of Remark rem:fh_ceiling is then a straight line.

    ``Pi_FH`` draws that ceiling, ``1 / (Pi_FH L)``. It is emitted first so the
    data series sit on top of it, and it is given a plain dashed grey rather
    than a deployment colour, since it is a bound and not a measurement.

    Args:
        results_by_deployment: Mapping ``Deployment -> [OperatingResult]``,
            ordered by AP count.
        path: Destination ``.tex``.
        colocated_result: The single-site reference point, or ``None``.
        Pi_FH: Fronthaul traffic coefficient [W per bit/s]; ``None`` omits the
            ceiling.
        xlabel, ylabel: Axis labels, in LaTeX.
        width, height: pgfplots dimensions.

    Returns:
        The path written.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    seen = [d for d, r in results_by_deployment.items() if r]
    legend = list(seen)
    if colocated_result is not None:
        legend = [Deployment.COLOCATED] + legend

    out = [
        "% Generated by scripts/eval4_ee_vs_aps.py -- do not edit by hand.",
        "% Requires pgfplots (already in the preamble).",
        _color_definitions(legend),
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        f"  width={width}, height={height},",
        f"  xlabel={{{xlabel}}}, ylabel={{{ylabel}}},",
        "  xmode=log, log basis x=2, xtick={1,2,4,8,16,32,64,128},",
        "  xticklabels={1,2,4,8,16,32,64,128},",
        "  xmin=0.85, xmax=165, ymode=log,",
        "  grid=both, grid style={line width=0.2pt, draw=gray!25},",
        "  tick label style={font=\\scriptsize},",
        "  label style={font=\\footnotesize},",
        "  legend style={font=\\scriptsize, draw=none, fill=none,",
        "                at={(0.02,0.02)}, anchor=south west, legend columns=1},",
        "]",
    ]

    if Pi_FH:
        lo, hi = 1.0, 200.0
        coords = (f"({lo:g},{1.0 / (Pi_FH * lo) * 1e-6:.6g}) "
                  f"({hi:g},{1.0 / (Pi_FH * hi) * 1e-6:.6g})")
        out.append("  \\addplot[dashed, gray!70!black, line width=0.9pt, forget plot] "
                   f"coordinates {{{coords}}};")

    if colocated_result is not None:
        out.append(_series(Deployment.COLOCATED, [colocated_result],
                           lambda r: 1, lambda r: r.energy_efficiency * 1e-6))
    for deployment in seen:
        out.append(_series(deployment, list(results_by_deployment[deployment]),
                           lambda r: r.L, lambda r: r.energy_efficiency * 1e-6))
    out.append("  \\legend{" + ", ".join(_PGF_LABEL[d] for d in legend) + "}")

    if Pi_FH:
        # Label the bound in place rather than in the legend: it is a reference
        # line, and a legend entry would read as a fourth deployment.
        out.append("  \\node[anchor=south west, font=\\scriptsize, gray!70!black]")
        out.append("    at (axis cs:1.15,"
                   f"{1.0 / (Pi_FH * 1.15) * 1e-6:.6g}) "
                   "{$1/(\\Pi_{\\mathrm{FH}}L)$};")

    out += ["\\end{axis}", "\\end{tikzpicture}", ""]

    path.write_text("\n".join(out), encoding="utf-8")
    return path


def _block_color_name(block: str) -> str:
    return "blk" + block.replace(" ", "").replace("-", "")


def breakdown_vs_aps(results_by_deployment, path, *, colocated_result=None,
                     xlabel=r"number of APs $L$",
                     ylabel=r"$P_{\mathrm{net}}$ [W]",
                     width="0.31\\textwidth", height="5.2cm") -> Path:
    """Write a one-row ``groupplot`` of stacked per-block power over the sweep.

    One panel per split, each a stacked bar chart over the AP count, using the
    block colours of :mod:`dmimo_power.plotting` so this figure and the totals
    of :func:`power_vs_aps` can be read against each other. The co-located
    deployment is the leftmost bar of every panel, marked ``1*`` to record that
    it is the single-site model rather than a one-AP network.

    Each panel scales to its own data. A common ceiling was tried and rejected:
    the totals span a factor five across the splits, so it flattens the S1 panel
    to a fifth of its height and hides exactly the block structure this figure
    exists to show. The cross-panel comparison is carried by
    :func:`power_vs_aps`, which puts all three totals on one axis, so nothing is
    lost by letting the panels here scale independently. The caption has to say
    so, since unequal panel scales are otherwise easy to miss.

    Args:
        results_by_deployment: Mapping ``Deployment -> [OperatingResult]``.
        path: Destination ``.tex``.
        colocated_result: Single-site reference, drawn first in every panel.
        xlabel, ylabel: Axis labels, in LaTeX.
        width, height: pgfplots dimensions of one panel.

    Returns:
        The path written.
    """
    from .plotting import _blocks_of

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    deployments = [d for d, r in results_by_deployment.items() if r]
    blocks = list(BLOCK_COLOR)
    n = len(deployments)

    out = [
        "% Generated by scripts/eval23_ap_sweep.py -- do not edit by hand.",
        "% Requires pgfplots + groupplots (already in the preamble).",
        "\n".join(f"\\definecolor{{{_block_color_name(b)}}}{{HTML}}"
                  f"{{{BLOCK_COLOR[b].lstrip('#').upper()}}}" for b in blocks),
        "\\begin{tikzpicture}",
        "\\begin{groupplot}[",
        f"  group style={{group size={n} by 1, horizontal sep=0.95cm,",
        "                ylabels at=edge left},",
        f"  width={width}, height={height},",
        f"  xlabel={{{xlabel}}}, ylabel={{{ylabel}}},",
        # `bar width` lives in the /tikz namespace. An axis option list forwards
        # unknown keys there, but the shared option list of a groupplot does
        # not, so it has to be qualified or the run dies on an unknown key.
        "  ybar stacked, /tikz/bar width=4.2pt,",
        "  ymin=0, enlarge x limits=0.10,",
        "  grid=major, grid style={line width=0.2pt, draw=gray!25},",
        "  tick label style={font=\\scriptsize},",
        "  label style={font=\\footnotesize},",
        "  title style={font=\\footnotesize, yshift=-3pt},",
        "  legend style={font=\\footnotesize, draw=none, fill=none, legend columns=3,",
        "                /tikz/every even column/.append style={column sep=6pt}},",
        "]",
    ]

    for i, deployment in enumerate(deployments):
        points = list(results_by_deployment[deployment])
        labels = [str(r.L) for r in points]
        if colocated_result is not None:
            points = [colocated_result] + points
            labels = ["1*"] + labels

        opts = [f"title={{{_PGF_LABEL[deployment]}}}",
                "symbolic x coords={" + ",".join(labels) + "}",
                "xtick=data"]
        if i == 0:
            opts.append("legend to name=eval3legend")
        out.append("\\nextgroupplot[" + ", ".join(opts) + "]")

        for block in blocks:
            coords = " ".join(
                f"({lab},{_blocks_of(r).get(block, 0.0):.6g})"
                for lab, r in zip(labels, points))
            out.append(f"  \\addplot[fill={_block_color_name(block)}, draw=white, "
                       f"line width=0.2pt] coordinates {{{coords}}};")
        if i == 0:
            out.append("  \\legend{" + ", ".join(blocks) + "}")

    middle = (n + 1) // 2
    out += [
        "\\end{groupplot}",
        f"\\node[anchor=north, yshift=-1.0cm] at (group c{middle}r1.south)",
        "  {\\pgfplotslegendfromname{eval3legend}};",
        "\\end{tikzpicture}",
        "",
    ]
    path.write_text("\n".join(out), encoding="utf-8")
    return path
